[build]
  publish = "dist"
  command = "echo 'Building project...' && npm run build && echo 'Build finished with exit code $?'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 